config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"

  resources :users do
    resources :posts, only: [:index, :new, :create]
    resources :friend_requests
    resources :friendships
  end

  resources :posts, only: [:show, :edit, :update, :destroy] do
    resources :comments
    resources :likes
  end

  resources :profiles
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commenter, class_name: "User"
  belongs_to :post

  validates :body, presence: true, length: { minimum: 1 }

  scope :ordered, -> { order(id: :desc) }

  def created_time_formatted
    created_at.strftime("%b %-d, %Y - %l:%M %P")
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)

    if @comment.save
      redirect_to request.referrer
      flash[:notice] = "Comment posted."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :commenter_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<div class="ms-2 me-2 ps-3 pe-3">
  <% unless post.comments.count.zero? %>
    <hr class="border border-2 opacity-75">
    <p>Comments</p>
  <% end %>
  <% post.comments.ordered.each do |comment| %>
    <div class="mb-3 p-3 border rounded hover-shadow">
      <div class="d-flex align-items-center">
        <div>
          <%= image_tag comment.commenter.gravatar_url(default: :mm),
                      :class => "gravatar-comment me-1" %>
          <%= link_to "#{comment.commenter.username.capitalize}", user_path(comment.commenter),
            style: "text-decoration: none" %>
        </div>
          <p class="text-secondary m-0 ms-3">
            <%= comment.created_time_formatted %>
          </p>
      </div>
      <div class="ms-5" style="word-wrap: break-word">
        <%= comment.body %>
      </div>
    </div>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for :comment, url: post_comments_path(post.id) do |form| %>
  <div class="mb-4">
    <%= form.hidden_field :commenter_id, value: current_user.id %>
    <%= form.label :body, "Comment:", class: "mb-2" %>
    <%= form.text_area :body, rows: 4, placeholder: "Enter your text here...",
                        class: "form-control bg-light", required: "required" %>
  </div>
  <div class="modal-footer pb-0">
    <button type="button" class="btn btn-secondary ms-3" data-bs-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary ms-3" data-bs-dismiss="modal">Post Comment</button>
  </div>
<% end %>

app/views/comments/index.html.erb
<% post.comments.each do |comment| %>
  <%= comment.body %>
<% end %>

app/views/comments/new.html.erb
<%= render "comments/form" post: @post %>