config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"

  resources :users do
    resources :posts, only: [:index, :new, :create]
    resources :friend_requests
    resources :friendships
  end

  resources :posts, only: [:show, :edit, :update, :destroy] do
    resources :comments
    resources :likes
  end

  resources :profiles
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  gravtastic
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: %i[facebook]

  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :initiated_friendships, foreign_key: :user_id, class_name: "Friendship", dependent: :destroy
  has_many :accepted_friendships, foreign_key: :friend_id, class_name: "Friendship", dependent: :destroy
  has_many :received_friend_requests, foreign_key: :receiver_id, class_name: "FriendRequest", dependent: :destroy
  has_many :sent_friend_requests, foreign_key: :sender_id, class_name: "FriendRequest", dependent: :destroy
  has_many :initiated_friends, through: :initiated_friendships, source: :friend, dependent: :destroy
  has_many :accepted_friends, through: :accepted_friendships, source: :user, dependent: :destroy
  has_many :comments, foreign_key: :commenter_id, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  validates :email, uniqueness: true
  validates :username, presence: true, uniqueness: true,
                       length: { maximum: 15, too_long: "can't be longer than 15 characters" }

  after_create :send_welcome_email

  def created_time_formatted
    created_at.strftime("%b %-d, %Y")
  end

  def friends
    initiated_friends + accepted_friends
  end

  def friend?(other_user)
    friends.include?(other_user)
  end

  def can_send_request_to?(other_user)
    !friend?(other_user) && self != other_user &&
      !sent_request_to?(other_user) && !received_request_from?(other_user)
  end

  def sent_request_to?(other_user)
    sent_friend_requests.any? { |request| request.receiver == other_user }
  end

  def received_request_from?(other_user)
    received_friend_requests.any? { |request| request.sender == other_user }
  end

  def random_strangers
    50.times.map { User.all.sample }
      .uniq.select { |user| can_send_request_to?(user) }
      .take(5)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.username = auth.info.name # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def send_welcome_email
    UserMailer.with(user: self).welcome_email.deliver_later
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
  skip_before_action :verify_authenticity_token, only: :facebook

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="row justify-content-center">
  <div class="row justify-content-center m-2 p-2", style="width: 650px">
    <div class="col-12">
      <h2 class="mt-1 mb-3 text-center"><span class="text-success"><%= User.count %></span> Odinbook users</h2>
      <hr>

      <ul class="mt-4", style="padding-left: 0">
        <% @users.each do |user| %>
          <% next if user == current_user %>
          <li class="user-card hover-shadow" style="list-style: none">
            <div class="shadow-sm bg-light p-3 mb-3 d-flex justify-content-between
                        align-items-center rounded">
              <div class="d-flex align-items-center">
                <%= image_tag user.gravatar_url(default: :mm),
                      :class => "gravatar-nav me-3", style: "height: 40px" %>
                <%= link_to "#{user.username.capitalize}", user_path(user.id),
                    style: "text-decoration: none", class: "fw-semibold" %>
              </div>
              <% if current_user.can_send_request_to?(user) %>
                <%= button_to "Add Friend",
                    user_friend_requests_path(user.id),
                    params: { friend_request: { sender_id: current_user.id,
                                                receiver_id: user.id
                                              }
                            },
                    class: "btn btn-primary"
                %>
              <% elsif current_user.sent_request_to?(user) %>
                <%= button_to "Cancel Friend Request",
                    user_friend_request_path(current_user.id, user.id),
                    method: :delete,
                    params: { friend_request: { sender_id: current_user.id,
                                                receiver_id: user.id
                                              }
                            },
                    class: "btn btn-secondary"
                %>
              <% elsif current_user.friend?(user) %>
                <div class="text-success me-1"><%= "Friend" %></div>
              <% elsif current_user.received_request_from?(user) %>
                <div class="d-flex">
                  <%= button_to "Accept",
                      user_friendships_path(current_user.id),
                      params: { friendship: { user_id: user.id,
                                              friend_id: current_user.id
                                            }
                              },
                      class: "btn btn-success me-2"
                  %>
                  <%= button_to "Decline",
                      user_friend_request_path(current_user.id, user.id),
                      method: :delete,
                      params: { friend_request: { sender_id: user.id,
                                                  receiver_id: current_user.id
                                                }
                              },
                      class: "btn btn-danger"
                  %>
                </div>
              <% end %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row m-2 p-4 justify-content-center">
  <div class="col-2 h-100 me-5 border rounded p-4 shadow-sm">
    <div class="d-flex flex-column w-75">
      <%= image_tag @user.gravatar_url(default: :mm),
          class: "gravatar border w-100" %>
      <h3 class="text-primary mt-3" style="word-wrap: break-word"><%= @user.username.capitalize %></h3>
    </div>
    <hr class="m-0 mb-2">

    <p class="m-2"><b><%= "#{@user.posts.count} " %></b><%= "post".pluralize(@user.posts.count) %><span class="ms-3 me-3">·</span><b><%= "#{@user.friends.count} " %></b><%= "friend".pluralize(@user.friends.count) %></p>
    <hr class="mt-1">

    <% if @user == current_user %>
      <% if current_user.profile %>
        <%= button_to "Edit profile", edit_profile_path(current_user), method: "get",
          class: "btn bg-warning bg-opacity-50 hover-bg-warning w-100 mb-4" %>
      <% elsif @user.profile.nil? %>
        <%= button_to "Add profile info", new_profile_path(@user),
            method: "get", class: "btn btn-success w-100 mb-3" %>
      <% end %>
    <% end %>

    <div class="d-flex flex-column">
      <% if @user.profile %>
        <%= render "profiles/info", user: @user %>
      <% else %>
        <%= render "profiles/empty" %>
      <% end %>
    </div>

    <% if current_user.can_send_request_to?(@user) %>
      <%= button_to "Add Friend", user_friend_requests_path(@user.id),
          params: { friend_request: { sender_id: current_user.id,
                                      receiver_id: @user.id
                                    }
                  },
          class: "btn btn-primary w-100"
      %>
    <% elsif current_user.sent_request_to?(@user) %>
      <%= button_to "Cancel Friend Request",
          user_friend_request_path(current_user.id, @user.id),
          method: :delete,
          params: { friend_request: { sender_id: current_user.id,
                                      receiver_id: @user.id
                                    }
                  },
          class: "btn btn-secondary w-100"
      %>
    <% elsif @user.friend?(current_user) %>
      <%= button_to "Remove Friend",
          user_friendship_path(@user.id, current_user.id),
          method: :delete,
          params: { friendship: { user_id: current_user.id, friend_id: @user.id }},
          class: "btn btn-danger w-100" %>
    <% elsif current_user.received_request_from?(@user) %>
      <hr>
      <p class="text-center">
        <%= "#{@user.username.capitalize} has added you as a friend." %>
      </p>
      <div class="d-flex justify-content-center">
        <%= button_to "Accept", user_friendships_path(current_user.id),
            params: { friendship: { user_id: @user.id,
                                    friend_id: current_user.id
                                  }
                    },
            class: "btn btn-success me-2"
        %>
        <%= button_to "Decline", user_friend_request_path(current_user.id, @user.id),
            method: :delete,
            params: { friend_request: { sender_id: @user.id,
                                        receiver_id: current_user.id
                                      }
                    },
            class: "btn btn-danger"
        %>
      </div>
    <% end %>
  </div>
  <div class="col-9 w-50">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home-tab-pane" type="button" role="tab" aria-controls="home-tab-pane" aria-selected="true">Posts</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="false">Friends</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="liked-posts-tab" data-bs-toggle="tab" data-bs-target="#liked-posts-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="false">Liked posts</button>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="home-tab-pane" role="tabpanel" aria-labelledby="home-tab" tabindex="0">
        <% if @user.posts.count.zero? %>
          <div class="p-3 text-secondary">
            <%= "No posts"%>
          </div>
        <% else %>
          <%= render "posts/user_posts", user: @user%>
        <% end %>
      </div>
      <div class="tab-pane fade" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="0">
        <% if @user.friends.count.zero? %>
          <div class="p-3 text-secondary">
            <%= "No friends"%>
          </div>
        <% else %>
          <%= render "friendships/friends", user: @user %>
        <% end %>
      </div>
      <div class="tab-pane fade" id="liked-posts-tab-pane" role="tabpanel" aria-labelledby="liked-posts-tab" tabindex="0">
        <% if @user.liked_posts.count.zero? %>
          <div class="p-3 text-secondary">
            <%= "#{@user.username.capitalize} has not liked any posts" %>
          </div>
        <% else %>
          <%= render "posts/liked_posts", user: @user %>
        <% end %>
      </div>
      <div class="tab-pane fade" id="contact-tab-pane" role="tabpanel" aria-labelledby="contact-tab" tabindex="0">...</div>
      <div class="tab-pane fade" id="disabled-tab-pane" role="tabpanel" aria-labelledby="disabled-tab" tabindex="0">...</div>
    </div>
  </div>
</div>