config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"

  resources :users do
    resources :posts, only: [:index, :new, :create]
    resources :friend_requests
    resources :friendships
  end

  resources :posts, only: [:show, :edit, :update, :destroy] do
    resources :comments
    resources :likes
  end

  resources :profiles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commenter, class_name: "User"
  belongs_to :post

  validates :body, presence: true, length: { minimum: 1 }

  scope :ordered, -> { order(id: :desc) }

  def created_time_formatted
    created_at.strftime("%b %-d, %Y - %l:%M %P")
  end
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: "User"
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :body, presence: true, length: { in: 1..500 }

  scope :ordered, -> { order(id: :desc) }

  def created_time_formatted
    created_at.strftime("%b %-d, %Y - %l:%M %P")
  end

  def liked_by?(user)
    likes.any? { |like| like.user == user }
  end

  def find_like(user)
    likes.find_by(user: user)
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  def display_name
    name.empty? ? "" : name.titleize
  end

  def display_gender
    gender.empty? ? "" : gender.capitalize
  end

  def display_age
    age.nil? ? "" : age
  end

  def display_location
    location.empty? ? "" : location.titleize
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  gravtastic
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: %i[facebook]

  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :initiated_friendships, foreign_key: :user_id, class_name: "Friendship", dependent: :destroy
  has_many :accepted_friendships, foreign_key: :friend_id, class_name: "Friendship", dependent: :destroy
  has_many :received_friend_requests, foreign_key: :receiver_id, class_name: "FriendRequest", dependent: :destroy
  has_many :sent_friend_requests, foreign_key: :sender_id, class_name: "FriendRequest", dependent: :destroy
  has_many :initiated_friends, through: :initiated_friendships, source: :friend, dependent: :destroy
  has_many :accepted_friends, through: :accepted_friendships, source: :user, dependent: :destroy
  has_many :comments, foreign_key: :commenter_id, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  validates :email, uniqueness: true
  validates :username, presence: true, uniqueness: true,
                       length: { maximum: 15, too_long: "can't be longer than 15 characters" }

  after_create :send_welcome_email

  def created_time_formatted
    created_at.strftime("%b %-d, %Y")
  end

  def friends
    initiated_friends + accepted_friends
  end

  def friend?(other_user)
    friends.include?(other_user)
  end

  def can_send_request_to?(other_user)
    !friend?(other_user) && self != other_user &&
      !sent_request_to?(other_user) && !received_request_from?(other_user)
  end

  def sent_request_to?(other_user)
    sent_friend_requests.any? { |request| request.receiver == other_user }
  end

  def received_request_from?(other_user)
    received_friend_requests.any? { |request| request.sender == other_user }
  end

  def random_strangers
    50.times.map { User.all.sample }
      .uniq.select { |user| can_send_request_to?(user) }
      .take(5)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.username = auth.info.name # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def send_welcome_email
    UserMailer.with(user: self).welcome_email.deliver_later
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)

    if @comment.save
      redirect_to request.referrer
      flash[:notice] = "Comment posted."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :commenter_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.create(like_params)
  end

  def destroy
    @post = Post.find(params[:id])
    @like = @post.likes.find_by(like_params)
    @like.destroy
  end

  private

  def like_params
    params.require(:like).permit(:user_id, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to root_path
      flash[:notice] = "New post created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_back(fallback_location: root_path)
    flash[:alert] = "Post deleted."
  end

  private

  def post_params
    params.require(:post).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Odinbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  <style>
    .gravatar-nav {
      height: 25px;
      width: auto;
      border-radius: 50%;
    }

    .gravatar {
      height: auto;
      width: 150px;
      border-radius: 50%;
    }

    .gravatar-home {
      height: 50px;
      width: auto;
      border-radius: 50%;
    }

    .gravatar-comment {
      height: 35px;
      width: auto;
      border-radius: 50%;
    }

    .delete-button svg:hover {
      color: red;
      transform: scale(1.2);
    }

    .hover-color {
      transition: 0.2s;
    }

    .hover-color:hover {
      color: #78e9ff !important;
    }

    .user-card {
      transition: 0.3s;
    }

    .user-card:hover {
      transform: scale(1.01);
      box-shadow: rgba(99, 99, 99, 0.2) 0px 2px 8px 0px !important;
    }

    .hover-shadow:hover {
      box-shadow: rgba(99, 99, 99, 0.2) 0px 2px 8px 0px !important;
      transition: 0.2s;
    }

    .hover-shadow-dark:hover {
      box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px !important;
      transition: 0.3s;
    }

    .like-count:hover, .comment-count:hover {
      color: #0d6efd !important;
    }

    .hover-bg-warning:hover {
      background-color: #ffc107 !important;
    }

    .nav-tabs .nav-item .nav-link {
      color: grey;
    }

    .nav-tabs .nav-item .nav-link.active {
      color: #0080FF;
    }

    .affix {
      top: 100px;
    }

    .field_with_errors { 
      display: inline;
    }

    .hover-border:after {
      display: block;
      content: '';
      border-bottom: solid 3px #ffc107;
      transform: scaleX(0);
      transition: transform 300ms ease-in-out;
    }

    .hover-border:hover:after {
      transform: scaleX(1);
    }
  </style>
  </head>

  <body>
    <%= render "shared/navbar" %>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-expand-lg sticky-top p-2 bg-dark text-white shadow">
    <div class="container-fluid">
      <a class="navbar-brand text-info fs-4 fw-bold hover-border hover-color" href="/">Odinbook</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse ms-2" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Create Post", new_user_post_path(current_user.id),
                class: "nav-link text-light me-2 hover-color hover-border" %>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light hover-color hover-border" href="/users">
              Discover Users
            </a>
          </li>
        </ul>

        <li class="nav-item dropdown me-4 mb-2 mt-2 pt-2 pb-2 nav-link">
          <a class="nav-link text-light hover-color" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <svg style="width:24px;height:24px" viewBox="0 0 24 24">
              <path fill="currentColor" d="M21,19V20H3V19L5,17V11C5,7.9 7.03,5.17 10,4.29C10,4.19 10,4.1 10,4A2,2 0 0,1 12,2A2,2 0 0,1 14,4C14,4.1 14,4.19 14,4.29C16.97,5.17 19,7.9 19,11V17L21,19M14,21A2,2 0 0,1 12,23A2,2 0 0,1 10,21" />
            </svg>
          </a>
          <ul class="dropdown-menu" style="min-width: 170px">
            <p class="px-3 pt-2 mt-n1 d-block mb-0" style="text-decoration: none">
              Friend requests
            </p>
            <hr class="dropdown-divider">
            <%= render "shared/notifications" %>
          </ul>
        </li>

        <li class="nav-item dropdown me-4 mb-2 mt-2 pt-2 pb-2 nav-link">
          <a class="nav-link dropdown-toggle text-light hover-color" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= image_tag current_user.gravatar_url(default: :mm),
                class: "gravatar-nav" %>
          </a>
          <ul class="dropdown-menu" style="min-width:60px">
            <p class="px-3 pt-2 mt-n1 d-block mb-0" style="text-decoration: none">
              Welcome, <span class="fw-bold"><%= current_user.username.titleize %></span>!
            </p>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Your Profile", user_path(current_user.id),
                    class: "dropdown-item" %></li>
            <li><%= link_to "Settings", edit_user_registration_path,
                    class: "dropdown-item" %></li>
          </ul>
        </li>

        <%= button_to "Logout", destroy_user_session_path, method: :delete,
            class: 'btn btn-outline-light', data: { turbo: false }
        %>
      </div>
    </div>
  </nav>
<% else %>
  <nav class="navbar navbar-expand-lg sticky-top p-2 bg-dark text-white shadow">
    <div class="container-fluid">
      <a class="navbar-brand text-info fs-4 fw-bold" href="/">Odinbook</a>
    </div>
  </nav>
<% end %>

app/views/shared/_notifications.html.erb
<% current_user.received_friend_requests.each do |request| %>
  <li>
    <%= link_to "#{request.sender.username.capitalize}",
        user_path(request.sender.id), class: "dropdown-item text-primary" %>
  </li>
<% end %>

<% if current_user.received_friend_requests.count.zero? %>
  <li class="dropdown-item"><%= "None" %></li>
<% else %>
  <hr class="dropdown-divider">
  <%= link_to "View all", user_friend_requests_path(current_user),
      class: "dropdown-item" %>
<% end %>

app/views/shared/_suggested_users.html.erb
<% user.random_strangers.each do |stranger| %>
  <div class="m-3">
    <%= image_tag stranger.gravatar_url(default: :mm),
                  :class => "gravatar-comment me-1" %>
    <%= link_to "#{stranger.username.capitalize}", user_path(stranger.id),
                style: "text-decoration: none" %>
  </div>
<% end %>