config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"

  resources :users do
    resources :posts, only: [:index, :new, :create]
    resources :friend_requests
    resources :friendships
  end

  resources :posts, only: [:show, :edit, :update, :destroy] do
    resources :comments
    resources :likes
  end

  resources :profiles
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: "User"
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :body, presence: true, length: { in: 1..500 }

  scope :ordered, -> { order(id: :desc) }

  def created_time_formatted
    created_at.strftime("%b %-d, %Y - %l:%M %P")
  end

  def liked_by?(user)
    likes.any? { |like| like.user == user }
  end

  def find_like(user)
    likes.find_by(user: user)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to root_path
      flash[:notice] = "New post created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_back(fallback_location: root_path)
    flash[:alert] = "Post deleted."
  end

  private

  def post_params
    params.require(:post).permit(:body)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_liked_posts.html.erb
<% user.liked_posts.ordered.each do |post| %>
  <%= render "posts/post", post: post %>
<% end %>

app/views/posts/_post.html.erb
<div class="container mt-3 mb-4 p-3 border shadow-sm rounded hover-shadow-dark" style="background-color: #fff">
  <div class="row">
    <%= image_tag post.author.gravatar_url(default: :mm),
                  :class => "gravatar-home" %>
    <div class="col row ps-1">
      <%= link_to "#{post.author.username.capitalize}", user_path(post.author.id),
                  class: "fw-semibold text-primary text-decoration-none" %>
      <div class="d-flex justify-content-between">
        <p class="text-secondary" style="display: inline-block">
          <%= post.created_time_formatted %>
        </p>
        <% if post.author == current_user %>
          <%= button_to post_path(post),
                        method: :delete,
                        data: {
                                turbo_confirm: "Are you sure?"
                              },
                        class: "btn btn-sm text-secondary delete-button me-4 opacity-75",
                        style: "border: none" do
          %>
            <svg style="width:24px;height:24px" viewBox="0 0 24 24">
              <path fill="currentColor" d="M9,3V4H4V6H5V19A2,2 0 0,0 7,21H17A2,2 0 0,0 19,19V6H20V4H15V3H9M9,8H11V17H9V8M13,8H15V17H13V8Z" />
            </svg>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="container mb-4">
      <p class="fs-5" style="word-wrap: break-word"><%= post.body %></p>
    </div>

    <div class="d-flex ms-2 ps-1 justify-content-between align-items-center">
      <div class="d-flex">
        <%= turbo_frame_tag "post_#{post.id}" do %>
          <div>
            <% like = post.find_like(current_user) %>
            <% if post.liked_by?(current_user) %>
              <%= button_to post_like_path(like, post, like: { user_id: current_user.id, post_id: post.id }),
                            method: :delete,
                            class: "btn btn-primary btn-sm d-flex align-items-center" do
              %>
                    <svg class="me-1" style="width:24px;height:24px" viewBox="0 0 24 24">
                      <path fill="currentColor" d="M23,10C23,8.89 22.1,8 21,8H14.68L15.64,3.43C15.66,3.33 15.67,3.22 15.67,3.11C15.67,2.7 15.5,2.32 15.23,2.05L14.17,1L7.59,7.58C7.22,7.95 7,8.45 7,9V19A2,2 0 0,0 9,21H18C18.83,21 19.54,20.5 19.84,19.78L22.86,12.73C22.95,12.5 23,12.26 23,12V10M1,21H5V9H1V21Z" />
                    </svg>
                    Liked
              <% end %>
            <% else %>
              <%= button_to post_likes_path(post, like: { user_id: current_user.id, post_id: post.id }),
                            class: "btn btn-outline-primary btn-sm d-flex" do
              %>
                    <svg class="me-1" style="width:24px;height:24px" viewBox="0 0 24 24">
                      <path fill="currentColor" d="M5,9V21H1V9H5M9,21A2,2 0 0,1 7,19V9C7,8.45 7.22,7.95 7.59,7.59L14.17,1L15.23,2.06C15.5,2.33 15.67,2.7 15.67,3.11L15.64,3.43L14.69,8H21C22.11,8 23,8.9 23,10V12C23,12.26 22.95,12.5 22.86,12.73L19.84,19.78C19.54,20.5 18.83,21 18,21H9M9,19H18.03L21,12V10H12.21L13.34,4.68L9,9.03V19Z" />
                    </svg>
                    Like
              <% end %>
            <% end %>
          </div>
        <% end %>

        <button type="button" class="btn btn-outline-primary btn-sm ms-3" data-bs-toggle="modal" data-bs-target="#commentModal<%= post.id %>" data-bs-whatever="@mdo">
          <svg style="width:24px;height:24px" viewBox="0 0 24 24">
            <path fill="currentColor" d="M20 2H4C2.9 2 2 2.9 2 4V22L6 18H20C21.1 18 22 17.1 22 16V4C22 2.9 21.1 2 20 2M20 16H5.2L4 17.2V4H20V16Z" />
          </svg>
          Comment
        </button>
      </div>

      <div class="d-flex me-3 justify-content-start align-items-center">
        <%= turbo_frame_tag "post_#{post.id}_like_count" do %>
          <a class="text-secondary me-2 like-count text-decoration-none" data-bs-toggle="collapse" href="#collapseLike<%= post.id %>" role="button" aria-expanded="false" aria-controls="collapseExample">
            <%= pluralize(post.likes.count, "Like") %>
          </a>
        <% end %>
        <a class="text-secondary comment-count ms-1 text-decoration-none" data-bs-toggle="collapse" href="#collapseComment<%= post.id %>" role="button" aria-expanded="false" aria-controls="collapseExample">
          <%= pluralize(post.comments.count, "Comment") %>
        </a>
      </div>
    </div>
  </div>

  <div class="modal fade" id="commentModal<%= post.id %>" tabindex="-1" aria-labelledby="commentModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="commentModalLabel">New comment</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div>
            <%= render "comments/form", post: post %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="collapse" id="collapseComment<%= post.id %>">
    <%= render "comments/comments", post: post%>
  </div>

  <div class="collapse ms-2 me-2 ps-3 pe-3" id="collapseLike<%= post.id %>">
    <% unless post.likes.count.zero? %>
      <hr class="border border-2 opacity-75">
      <p>Liked by</p>
    <% end %>

    <div>
      <% post.likes.each do |like| %>
        <div class="ps-2 pe-2">
          <div>
            <div class="mb-2">
              <%= image_tag like.user.gravatar_url(default: :mm),
                            :class => "gravatar-comment me-1" %>
              <%= link_to "#{like.user.username.capitalize}",
                          user_path(like.user),
                          class: "text-decoration-none" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_user_posts.html.erb
<% user.posts.ordered.each do |post| %>
  <%= render "posts/post", post: post %>
<% end %>

app/views/posts/index.html.erb
<div class="bg-light" style="margin-top: -17px">
  <div class="container pt-5 pt-2">
    <h5 class="text-start text-secondary">Latest Posts</h5>
    <div class="row justify-content-between mt-2">
      <div class="col-8">
        <% @posts.ordered.each do |post| %>
          <%= render "post", post: post %>
        <% end %>
      </div>
      <div class="col-3 h-25 mt-3 d-flex flex-column sticky-top affix" style="z-index: 100">
        <div class="border rounded shadow-sm hover-shadow-dark bg-white">
          <h6 class="text-secondary m-3 mb-4">Suggested Users</h6>
          <%= render "shared/suggested_users", user: current_user %>
        </div>
        <div class="border rounded mt-4 mb-5 pb-3 shadow-sm hover-shadow-dark bg-white">
          <h6 class="text-secondary m-3 mb-3">Newest User</h6>
          <div class="m-3 mb-0">
            <%= image_tag User.last.gravatar_url(default: :mm),
                          :class => "gravatar-comment me-1" %>
            <%= link_to User.last.username.titleize, user_path(User.last),
                        style: "text-decoration: none" %>
          </div>
        </div>
        <div class="mt-5">
          <a href="javascript:window.scrollTo(0,0);" class="text-decoration-none text-secondary">Go to top</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="row justify-content-center m-4 p-4">
  <div class="col-6">
    <%= form_with(model: @post, url: user_posts_path(current_user.id)) do |form| %>
      <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being created:</h2>
          <ul>
            <% @post.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-3">
        <%= form.label :body, "What's on your mind?", class: "form-label fs-3" %>
        <%= form.text_area :body, cols: 30, rows: 10,
                            placeholder: "Enter your text here",
                            class: "form-control bg-light shadow-sm",
                            autofocus: true %>
        <%= form.submit "Post", class: "btn btn-primary mt-4" %>
        <%= link_to "Cancel", :back, class: "btn btn-outline-primary mt-4 ms-2"%>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container mt-5">
  <div class="row justify-content-between">
    <div class="col-8">
      <%= link_to "Home", root_path, style: "text-decoration: none" %>
        <%= render "post", post: @post %>
      <%= link_to "< Back", :back, style: "text-decoration: none" %>
    </div>
  </div>
</div>